// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/INFURA/project-harald-rudell/models"
)

// GetV1JsonrpcNetworkMethodReader is a Reader for the GetV1JsonrpcNetworkMethod structure.
type GetV1JsonrpcNetworkMethodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1JsonrpcNetworkMethodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1JsonrpcNetworkMethodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetV1JsonrpcNetworkMethodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetV1JsonrpcNetworkMethodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetV1JsonrpcNetworkMethodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 502:
		result := NewGetV1JsonrpcNetworkMethodBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1JsonrpcNetworkMethodOK creates a GetV1JsonrpcNetworkMethodOK with default headers values
func NewGetV1JsonrpcNetworkMethodOK() *GetV1JsonrpcNetworkMethodOK {
	return &GetV1JsonrpcNetworkMethodOK{}
}

/*GetV1JsonrpcNetworkMethodOK handles this case with default header values.

JSON-RPC response
*/
type GetV1JsonrpcNetworkMethodOK struct {
	Payload *models.JSONRPCResponse
}

func (o *GetV1JsonrpcNetworkMethodOK) Error() string {
	return fmt.Sprintf("[GET /v1/jsonrpc/{network}/{method}][%d] getV1JsonrpcNetworkMethodOK  %+v", 200, o.Payload)
}

func (o *GetV1JsonrpcNetworkMethodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONRPCResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1JsonrpcNetworkMethodBadRequest creates a GetV1JsonrpcNetworkMethodBadRequest with default headers values
func NewGetV1JsonrpcNetworkMethodBadRequest() *GetV1JsonrpcNetworkMethodBadRequest {
	return &GetV1JsonrpcNetworkMethodBadRequest{}
}

/*GetV1JsonrpcNetworkMethodBadRequest handles this case with default header values.

Bad JSON in `params` query parameter
*/
type GetV1JsonrpcNetworkMethodBadRequest struct {
}

func (o *GetV1JsonrpcNetworkMethodBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/jsonrpc/{network}/{method}][%d] getV1JsonrpcNetworkMethodBadRequest ", 400)
}

func (o *GetV1JsonrpcNetworkMethodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetV1JsonrpcNetworkMethodNotFound creates a GetV1JsonrpcNetworkMethodNotFound with default headers values
func NewGetV1JsonrpcNetworkMethodNotFound() *GetV1JsonrpcNetworkMethodNotFound {
	return &GetV1JsonrpcNetworkMethodNotFound{}
}

/*GetV1JsonrpcNetworkMethodNotFound handles this case with default header values.

JSON-RPC method is not a valid GET method
*/
type GetV1JsonrpcNetworkMethodNotFound struct {
}

func (o *GetV1JsonrpcNetworkMethodNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/jsonrpc/{network}/{method}][%d] getV1JsonrpcNetworkMethodNotFound ", 404)
}

func (o *GetV1JsonrpcNetworkMethodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetV1JsonrpcNetworkMethodInternalServerError creates a GetV1JsonrpcNetworkMethodInternalServerError with default headers values
func NewGetV1JsonrpcNetworkMethodInternalServerError() *GetV1JsonrpcNetworkMethodInternalServerError {
	return &GetV1JsonrpcNetworkMethodInternalServerError{}
}

/*GetV1JsonrpcNetworkMethodInternalServerError handles this case with default header values.

Server error
*/
type GetV1JsonrpcNetworkMethodInternalServerError struct {
}

func (o *GetV1JsonrpcNetworkMethodInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/jsonrpc/{network}/{method}][%d] getV1JsonrpcNetworkMethodInternalServerError ", 500)
}

func (o *GetV1JsonrpcNetworkMethodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetV1JsonrpcNetworkMethodBadGateway creates a GetV1JsonrpcNetworkMethodBadGateway with default headers values
func NewGetV1JsonrpcNetworkMethodBadGateway() *GetV1JsonrpcNetworkMethodBadGateway {
	return &GetV1JsonrpcNetworkMethodBadGateway{}
}

/*GetV1JsonrpcNetworkMethodBadGateway handles this case with default header values.

Ethereum client error
*/
type GetV1JsonrpcNetworkMethodBadGateway struct {
}

func (o *GetV1JsonrpcNetworkMethodBadGateway) Error() string {
	return fmt.Sprintf("[GET /v1/jsonrpc/{network}/{method}][%d] getV1JsonrpcNetworkMethodBadGateway ", 502)
}

func (o *GetV1JsonrpcNetworkMethodBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
