// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/INFURA/project-harald-rudell/models"
)

// GetV1JsonrpcNetworkMethodsReader is a Reader for the GetV1JsonrpcNetworkMethods structure.
type GetV1JsonrpcNetworkMethodsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1JsonrpcNetworkMethodsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1JsonrpcNetworkMethodsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetV1JsonrpcNetworkMethodsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1JsonrpcNetworkMethodsOK creates a GetV1JsonrpcNetworkMethodsOK with default headers values
func NewGetV1JsonrpcNetworkMethodsOK() *GetV1JsonrpcNetworkMethodsOK {
	return &GetV1JsonrpcNetworkMethodsOK{}
}

/*GetV1JsonrpcNetworkMethodsOK handles this case with default header values.

Methods response
*/
type GetV1JsonrpcNetworkMethodsOK struct {
	Payload *models.MethodsResponse
}

func (o *GetV1JsonrpcNetworkMethodsOK) Error() string {
	return fmt.Sprintf("[GET /v1/jsonrpc/{network}/methods][%d] getV1JsonrpcNetworkMethodsOK  %+v", 200, o.Payload)
}

func (o *GetV1JsonrpcNetworkMethodsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MethodsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1JsonrpcNetworkMethodsInternalServerError creates a GetV1JsonrpcNetworkMethodsInternalServerError with default headers values
func NewGetV1JsonrpcNetworkMethodsInternalServerError() *GetV1JsonrpcNetworkMethodsInternalServerError {
	return &GetV1JsonrpcNetworkMethodsInternalServerError{}
}

/*GetV1JsonrpcNetworkMethodsInternalServerError handles this case with default header values.

Server error
*/
type GetV1JsonrpcNetworkMethodsInternalServerError struct {
}

func (o *GetV1JsonrpcNetworkMethodsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/jsonrpc/{network}/methods][%d] getV1JsonrpcNetworkMethodsInternalServerError ", 500)
}

func (o *GetV1JsonrpcNetworkMethodsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
