// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/INFURA/project-harald-rudell/models"
)

// GetV1TickerSymbolsReader is a Reader for the GetV1TickerSymbols structure.
type GetV1TickerSymbolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1TickerSymbolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1TickerSymbolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1TickerSymbolsOK creates a GetV1TickerSymbolsOK with default headers values
func NewGetV1TickerSymbolsOK() *GetV1TickerSymbolsOK {
	return &GetV1TickerSymbolsOK{}
}

/*GetV1TickerSymbolsOK handles this case with default header values.

Symbols response
*/
type GetV1TickerSymbolsOK struct {
	Payload *models.SymbolsResponse
}

func (o *GetV1TickerSymbolsOK) Error() string {
	return fmt.Sprintf("[GET /v1/ticker/symbols][%d] getV1TickerSymbolsOK  %+v", 200, o.Payload)
}

func (o *GetV1TickerSymbolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SymbolsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
