// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1JsonrpcNetworkMethodsParams creates a new GetV1JsonrpcNetworkMethodsParams object
// with the default values initialized.
func NewGetV1JsonrpcNetworkMethodsParams() *GetV1JsonrpcNetworkMethodsParams {
	var ()
	return &GetV1JsonrpcNetworkMethodsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1JsonrpcNetworkMethodsParamsWithTimeout creates a new GetV1JsonrpcNetworkMethodsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1JsonrpcNetworkMethodsParamsWithTimeout(timeout time.Duration) *GetV1JsonrpcNetworkMethodsParams {
	var ()
	return &GetV1JsonrpcNetworkMethodsParams{

		timeout: timeout,
	}
}

// NewGetV1JsonrpcNetworkMethodsParamsWithContext creates a new GetV1JsonrpcNetworkMethodsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1JsonrpcNetworkMethodsParamsWithContext(ctx context.Context) *GetV1JsonrpcNetworkMethodsParams {
	var ()
	return &GetV1JsonrpcNetworkMethodsParams{

		Context: ctx,
	}
}

// NewGetV1JsonrpcNetworkMethodsParamsWithHTTPClient creates a new GetV1JsonrpcNetworkMethodsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1JsonrpcNetworkMethodsParamsWithHTTPClient(client *http.Client) *GetV1JsonrpcNetworkMethodsParams {
	var ()
	return &GetV1JsonrpcNetworkMethodsParams{
		HTTPClient: client,
	}
}

/*GetV1JsonrpcNetworkMethodsParams contains all the parameters to send to the API endpoint
for the get v1 jsonrpc network methods operation typically these are written to a http.Request
*/
type GetV1JsonrpcNetworkMethodsParams struct {

	/*Network
	  Ethereum network in lowercase

	*/
	Network string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) WithTimeout(timeout time.Duration) *GetV1JsonrpcNetworkMethodsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) WithContext(ctx context.Context) *GetV1JsonrpcNetworkMethodsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) WithHTTPClient(client *http.Client) *GetV1JsonrpcNetworkMethodsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetwork adds the network to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) WithNetwork(network string) *GetV1JsonrpcNetworkMethodsParams {
	o.SetNetwork(network)
	return o
}

// SetNetwork adds the network to the get v1 jsonrpc network methods params
func (o *GetV1JsonrpcNetworkMethodsParams) SetNetwork(network string) {
	o.Network = network
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1JsonrpcNetworkMethodsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param network
	if err := r.SetPathParam("network", o.Network); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
