// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetV1BlacklistReader is a Reader for the GetV1Blacklist structure.
type GetV1BlacklistReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1BlacklistReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1BlacklistOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 502:
		result := NewGetV1BlacklistBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1BlacklistOK creates a GetV1BlacklistOK with default headers values
func NewGetV1BlacklistOK() *GetV1BlacklistOK {
	return &GetV1BlacklistOK{}
}

/*GetV1BlacklistOK handles this case with default header values.

List of blacklisted phishing domains
*/
type GetV1BlacklistOK struct {
	Payload []string
}

func (o *GetV1BlacklistOK) Error() string {
	return fmt.Sprintf("[GET /v1/blacklist][%d] getV1BlacklistOK  %+v", 200, o.Payload)
}

func (o *GetV1BlacklistOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1BlacklistBadGateway creates a GetV1BlacklistBadGateway with default headers values
func NewGetV1BlacklistBadGateway() *GetV1BlacklistBadGateway {
	return &GetV1BlacklistBadGateway{}
}

/*GetV1BlacklistBadGateway handles this case with default header values.

GitHub is having issues
*/
type GetV1BlacklistBadGateway struct {
}

func (o *GetV1BlacklistBadGateway) Error() string {
	return fmt.Sprintf("[GET /v1/blacklist][%d] getV1BlacklistBadGateway ", 502)
}

func (o *GetV1BlacklistBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
