// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1TickerSymbolParams creates a new GetV1TickerSymbolParams object
// with the default values initialized.
func NewGetV1TickerSymbolParams() *GetV1TickerSymbolParams {
	var ()
	return &GetV1TickerSymbolParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1TickerSymbolParamsWithTimeout creates a new GetV1TickerSymbolParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1TickerSymbolParamsWithTimeout(timeout time.Duration) *GetV1TickerSymbolParams {
	var ()
	return &GetV1TickerSymbolParams{

		timeout: timeout,
	}
}

// NewGetV1TickerSymbolParamsWithContext creates a new GetV1TickerSymbolParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1TickerSymbolParamsWithContext(ctx context.Context) *GetV1TickerSymbolParams {
	var ()
	return &GetV1TickerSymbolParams{

		Context: ctx,
	}
}

// NewGetV1TickerSymbolParamsWithHTTPClient creates a new GetV1TickerSymbolParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1TickerSymbolParamsWithHTTPClient(client *http.Client) *GetV1TickerSymbolParams {
	var ()
	return &GetV1TickerSymbolParams{
		HTTPClient: client,
	}
}

/*GetV1TickerSymbolParams contains all the parameters to send to the API endpoint
for the get v1 ticker symbol operation typically these are written to a http.Request
*/
type GetV1TickerSymbolParams struct {

	/*Symbol
	  Ticker symbol (currency pair)

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) WithTimeout(timeout time.Duration) *GetV1TickerSymbolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) WithContext(ctx context.Context) *GetV1TickerSymbolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) WithHTTPClient(client *http.Client) *GetV1TickerSymbolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSymbol adds the symbol to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) WithSymbol(symbol string) *GetV1TickerSymbolParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the get v1 ticker symbol params
func (o *GetV1TickerSymbolParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1TickerSymbolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
