// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1TickerSymbolsParams creates a new GetV1TickerSymbolsParams object
// with the default values initialized.
func NewGetV1TickerSymbolsParams() *GetV1TickerSymbolsParams {

	return &GetV1TickerSymbolsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1TickerSymbolsParamsWithTimeout creates a new GetV1TickerSymbolsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1TickerSymbolsParamsWithTimeout(timeout time.Duration) *GetV1TickerSymbolsParams {

	return &GetV1TickerSymbolsParams{

		timeout: timeout,
	}
}

// NewGetV1TickerSymbolsParamsWithContext creates a new GetV1TickerSymbolsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1TickerSymbolsParamsWithContext(ctx context.Context) *GetV1TickerSymbolsParams {

	return &GetV1TickerSymbolsParams{

		Context: ctx,
	}
}

// NewGetV1TickerSymbolsParamsWithHTTPClient creates a new GetV1TickerSymbolsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1TickerSymbolsParamsWithHTTPClient(client *http.Client) *GetV1TickerSymbolsParams {

	return &GetV1TickerSymbolsParams{
		HTTPClient: client,
	}
}

/*GetV1TickerSymbolsParams contains all the parameters to send to the API endpoint
for the get v1 ticker symbols operation typically these are written to a http.Request
*/
type GetV1TickerSymbolsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 ticker symbols params
func (o *GetV1TickerSymbolsParams) WithTimeout(timeout time.Duration) *GetV1TickerSymbolsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 ticker symbols params
func (o *GetV1TickerSymbolsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 ticker symbols params
func (o *GetV1TickerSymbolsParams) WithContext(ctx context.Context) *GetV1TickerSymbolsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 ticker symbols params
func (o *GetV1TickerSymbolsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 ticker symbols params
func (o *GetV1TickerSymbolsParams) WithHTTPClient(client *http.Client) *GetV1TickerSymbolsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 ticker symbols params
func (o *GetV1TickerSymbolsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1TickerSymbolsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
