// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV2BlacklistParams creates a new GetV2BlacklistParams object
// with the default values initialized.
func NewGetV2BlacklistParams() *GetV2BlacklistParams {

	return &GetV2BlacklistParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV2BlacklistParamsWithTimeout creates a new GetV2BlacklistParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV2BlacklistParamsWithTimeout(timeout time.Duration) *GetV2BlacklistParams {

	return &GetV2BlacklistParams{

		timeout: timeout,
	}
}

// NewGetV2BlacklistParamsWithContext creates a new GetV2BlacklistParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV2BlacklistParamsWithContext(ctx context.Context) *GetV2BlacklistParams {

	return &GetV2BlacklistParams{

		Context: ctx,
	}
}

// NewGetV2BlacklistParamsWithHTTPClient creates a new GetV2BlacklistParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV2BlacklistParamsWithHTTPClient(client *http.Client) *GetV2BlacklistParams {

	return &GetV2BlacklistParams{
		HTTPClient: client,
	}
}

/*GetV2BlacklistParams contains all the parameters to send to the API endpoint
for the get v2 blacklist operation typically these are written to a http.Request
*/
type GetV2BlacklistParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v2 blacklist params
func (o *GetV2BlacklistParams) WithTimeout(timeout time.Duration) *GetV2BlacklistParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v2 blacklist params
func (o *GetV2BlacklistParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v2 blacklist params
func (o *GetV2BlacklistParams) WithContext(ctx context.Context) *GetV2BlacklistParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v2 blacklist params
func (o *GetV2BlacklistParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v2 blacklist params
func (o *GetV2BlacklistParams) WithHTTPClient(client *http.Client) *GetV2BlacklistParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v2 blacklist params
func (o *GetV2BlacklistParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV2BlacklistParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
