// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/INFURA/project-harald-rudell/models"
)

// GetV1TickerSymbolFullReader is a Reader for the GetV1TickerSymbolFull structure.
type GetV1TickerSymbolFullReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1TickerSymbolFullReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetV1TickerSymbolFullOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetV1TickerSymbolFullOK creates a GetV1TickerSymbolFullOK with default headers values
func NewGetV1TickerSymbolFullOK() *GetV1TickerSymbolFullOK {
	return &GetV1TickerSymbolFullOK{}
}

/*GetV1TickerSymbolFullOK handles this case with default header values.

Full ticker response
*/
type GetV1TickerSymbolFullOK struct {
	Payload *models.TickerFullResponse
}

func (o *GetV1TickerSymbolFullOK) Error() string {
	return fmt.Sprintf("[GET /v1/ticker/{symbol}/full][%d] getV1TickerSymbolFullOK  %+v", 200, o.Payload)
}

func (o *GetV1TickerSymbolFullOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TickerFullResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
