// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetV1TickerSymbolFullParams creates a new GetV1TickerSymbolFullParams object
// with the default values initialized.
func NewGetV1TickerSymbolFullParams() *GetV1TickerSymbolFullParams {
	var ()
	return &GetV1TickerSymbolFullParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1TickerSymbolFullParamsWithTimeout creates a new GetV1TickerSymbolFullParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1TickerSymbolFullParamsWithTimeout(timeout time.Duration) *GetV1TickerSymbolFullParams {
	var ()
	return &GetV1TickerSymbolFullParams{

		timeout: timeout,
	}
}

// NewGetV1TickerSymbolFullParamsWithContext creates a new GetV1TickerSymbolFullParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1TickerSymbolFullParamsWithContext(ctx context.Context) *GetV1TickerSymbolFullParams {
	var ()
	return &GetV1TickerSymbolFullParams{

		Context: ctx,
	}
}

// NewGetV1TickerSymbolFullParamsWithHTTPClient creates a new GetV1TickerSymbolFullParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1TickerSymbolFullParamsWithHTTPClient(client *http.Client) *GetV1TickerSymbolFullParams {
	var ()
	return &GetV1TickerSymbolFullParams{
		HTTPClient: client,
	}
}

/*GetV1TickerSymbolFullParams contains all the parameters to send to the API endpoint
for the get v1 ticker symbol full operation typically these are written to a http.Request
*/
type GetV1TickerSymbolFullParams struct {

	/*Symbol
	  Ticker symbol (currency pair)

	*/
	Symbol string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) WithTimeout(timeout time.Duration) *GetV1TickerSymbolFullParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) WithContext(ctx context.Context) *GetV1TickerSymbolFullParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) WithHTTPClient(client *http.Client) *GetV1TickerSymbolFullParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSymbol adds the symbol to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) WithSymbol(symbol string) *GetV1TickerSymbolFullParams {
	o.SetSymbol(symbol)
	return o
}

// SetSymbol adds the symbol to the get v1 ticker symbol full params
func (o *GetV1TickerSymbolFullParams) SetSymbol(symbol string) {
	o.Symbol = symbol
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1TickerSymbolFullParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param symbol
	if err := r.SetPathParam("symbol", o.Symbol); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
