// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PostV3Projectid https://infura.io/docs/ethereum/json-rpc/eth_getBlockByNumber

*/
func (a *Client) PostV3Projectid(params *PostV3ProjectidParams) (*PostV3ProjectidOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV3ProjectidParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostV3Projectid",
		Method:             "POST",
		PathPattern:        "/v3/{projectid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostV3ProjectidReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostV3ProjectidOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
