// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/INFURA/project-harald-rudell/models"
)

// NewPostV1JsonrpcNetworkParams creates a new PostV1JsonrpcNetworkParams object
// with the default values initialized.
func NewPostV1JsonrpcNetworkParams() *PostV1JsonrpcNetworkParams {
	var ()
	return &PostV1JsonrpcNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1JsonrpcNetworkParamsWithTimeout creates a new PostV1JsonrpcNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostV1JsonrpcNetworkParamsWithTimeout(timeout time.Duration) *PostV1JsonrpcNetworkParams {
	var ()
	return &PostV1JsonrpcNetworkParams{

		timeout: timeout,
	}
}

// NewPostV1JsonrpcNetworkParamsWithContext creates a new PostV1JsonrpcNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostV1JsonrpcNetworkParamsWithContext(ctx context.Context) *PostV1JsonrpcNetworkParams {
	var ()
	return &PostV1JsonrpcNetworkParams{

		Context: ctx,
	}
}

// NewPostV1JsonrpcNetworkParamsWithHTTPClient creates a new PostV1JsonrpcNetworkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostV1JsonrpcNetworkParamsWithHTTPClient(client *http.Client) *PostV1JsonrpcNetworkParams {
	var ()
	return &PostV1JsonrpcNetworkParams{
		HTTPClient: client,
	}
}

/*PostV1JsonrpcNetworkParams contains all the parameters to send to the API endpoint
for the post v1 jsonrpc network operation typically these are written to a http.Request
*/
type PostV1JsonrpcNetworkParams struct {

	/*Network
	  Ethereum network in lowercase

	*/
	Network string
	/*Payload
	  Regular JSON-RPC payload (POST body)

	*/
	Payload models.JSONRPCRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) WithTimeout(timeout time.Duration) *PostV1JsonrpcNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) WithContext(ctx context.Context) *PostV1JsonrpcNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) WithHTTPClient(client *http.Client) *PostV1JsonrpcNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetwork adds the network to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) WithNetwork(network string) *PostV1JsonrpcNetworkParams {
	o.SetNetwork(network)
	return o
}

// SetNetwork adds the network to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) SetNetwork(network string) {
	o.Network = network
}

// WithPayload adds the payload to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) WithPayload(payload models.JSONRPCRequest) *PostV1JsonrpcNetworkParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the post v1 jsonrpc network params
func (o *PostV1JsonrpcNetworkParams) SetPayload(payload models.JSONRPCRequest) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1JsonrpcNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param network
	if err := r.SetPathParam("network", o.Network); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Payload); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
