// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/INFURA/project-harald-rudell/models"
)

// PostV1JsonrpcNetworkReader is a Reader for the PostV1JsonrpcNetwork structure.
type PostV1JsonrpcNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1JsonrpcNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostV1JsonrpcNetworkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostV1JsonrpcNetworkBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostV1JsonrpcNetworkNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostV1JsonrpcNetworkInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 502:
		result := NewPostV1JsonrpcNetworkBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostV1JsonrpcNetworkOK creates a PostV1JsonrpcNetworkOK with default headers values
func NewPostV1JsonrpcNetworkOK() *PostV1JsonrpcNetworkOK {
	return &PostV1JsonrpcNetworkOK{}
}

/*PostV1JsonrpcNetworkOK handles this case with default header values.

JSON-RPC response
*/
type PostV1JsonrpcNetworkOK struct {
	Payload *models.JSONRPCResponse
}

func (o *PostV1JsonrpcNetworkOK) Error() string {
	return fmt.Sprintf("[POST /v1/jsonrpc/{network}][%d] postV1JsonrpcNetworkOK  %+v", 200, o.Payload)
}

func (o *PostV1JsonrpcNetworkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONRPCResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1JsonrpcNetworkBadRequest creates a PostV1JsonrpcNetworkBadRequest with default headers values
func NewPostV1JsonrpcNetworkBadRequest() *PostV1JsonrpcNetworkBadRequest {
	return &PostV1JsonrpcNetworkBadRequest{}
}

/*PostV1JsonrpcNetworkBadRequest handles this case with default header values.

Bad JSON in POST body or missing Content-Type header
*/
type PostV1JsonrpcNetworkBadRequest struct {
}

func (o *PostV1JsonrpcNetworkBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/jsonrpc/{network}][%d] postV1JsonrpcNetworkBadRequest ", 400)
}

func (o *PostV1JsonrpcNetworkBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostV1JsonrpcNetworkNotFound creates a PostV1JsonrpcNetworkNotFound with default headers values
func NewPostV1JsonrpcNetworkNotFound() *PostV1JsonrpcNetworkNotFound {
	return &PostV1JsonrpcNetworkNotFound{}
}

/*PostV1JsonrpcNetworkNotFound handles this case with default header values.

JSON-RPC method is not a valid POST method
*/
type PostV1JsonrpcNetworkNotFound struct {
}

func (o *PostV1JsonrpcNetworkNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/jsonrpc/{network}][%d] postV1JsonrpcNetworkNotFound ", 404)
}

func (o *PostV1JsonrpcNetworkNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostV1JsonrpcNetworkInternalServerError creates a PostV1JsonrpcNetworkInternalServerError with default headers values
func NewPostV1JsonrpcNetworkInternalServerError() *PostV1JsonrpcNetworkInternalServerError {
	return &PostV1JsonrpcNetworkInternalServerError{}
}

/*PostV1JsonrpcNetworkInternalServerError handles this case with default header values.

Server error
*/
type PostV1JsonrpcNetworkInternalServerError struct {
}

func (o *PostV1JsonrpcNetworkInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/jsonrpc/{network}][%d] postV1JsonrpcNetworkInternalServerError ", 500)
}

func (o *PostV1JsonrpcNetworkInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostV1JsonrpcNetworkBadGateway creates a PostV1JsonrpcNetworkBadGateway with default headers values
func NewPostV1JsonrpcNetworkBadGateway() *PostV1JsonrpcNetworkBadGateway {
	return &PostV1JsonrpcNetworkBadGateway{}
}

/*PostV1JsonrpcNetworkBadGateway handles this case with default header values.

Ethereum client error
*/
type PostV1JsonrpcNetworkBadGateway struct {
}

func (o *PostV1JsonrpcNetworkBadGateway) Error() string {
	return fmt.Sprintf("[POST /v1/jsonrpc/{network}][%d] postV1JsonrpcNetworkBadGateway ", 502)
}

func (o *PostV1JsonrpcNetworkBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
