// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/INFURA/project-harald-rudell/models"
)

// PostV3ProjectidReader is a Reader for the PostV3Projectid structure.
type PostV3ProjectidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV3ProjectidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostV3ProjectidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostV3ProjectidBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostV3ProjectidNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostV3ProjectidInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 502:
		result := NewPostV3ProjectidBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostV3ProjectidOK creates a PostV3ProjectidOK with default headers values
func NewPostV3ProjectidOK() *PostV3ProjectidOK {
	return &PostV3ProjectidOK{}
}

/*PostV3ProjectidOK handles this case with default header values.

JSON-RPC response
*/
type PostV3ProjectidOK struct {
	Payload *models.JSONRPCResponse
}

func (o *PostV3ProjectidOK) Error() string {
	return fmt.Sprintf("[POST /v3/{projectid}][%d] postV3ProjectidOK  %+v", 200, o.Payload)
}

func (o *PostV3ProjectidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONRPCResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV3ProjectidBadRequest creates a PostV3ProjectidBadRequest with default headers values
func NewPostV3ProjectidBadRequest() *PostV3ProjectidBadRequest {
	return &PostV3ProjectidBadRequest{}
}

/*PostV3ProjectidBadRequest handles this case with default header values.

Bad JSON in `params` query parameter
*/
type PostV3ProjectidBadRequest struct {
}

func (o *PostV3ProjectidBadRequest) Error() string {
	return fmt.Sprintf("[POST /v3/{projectid}][%d] postV3ProjectidBadRequest ", 400)
}

func (o *PostV3ProjectidBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostV3ProjectidNotFound creates a PostV3ProjectidNotFound with default headers values
func NewPostV3ProjectidNotFound() *PostV3ProjectidNotFound {
	return &PostV3ProjectidNotFound{}
}

/*PostV3ProjectidNotFound handles this case with default header values.

JSON-RPC method is not a valid GET method
*/
type PostV3ProjectidNotFound struct {
}

func (o *PostV3ProjectidNotFound) Error() string {
	return fmt.Sprintf("[POST /v3/{projectid}][%d] postV3ProjectidNotFound ", 404)
}

func (o *PostV3ProjectidNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostV3ProjectidInternalServerError creates a PostV3ProjectidInternalServerError with default headers values
func NewPostV3ProjectidInternalServerError() *PostV3ProjectidInternalServerError {
	return &PostV3ProjectidInternalServerError{}
}

/*PostV3ProjectidInternalServerError handles this case with default header values.

Server error
*/
type PostV3ProjectidInternalServerError struct {
}

func (o *PostV3ProjectidInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v3/{projectid}][%d] postV3ProjectidInternalServerError ", 500)
}

func (o *PostV3ProjectidInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostV3ProjectidBadGateway creates a PostV3ProjectidBadGateway with default headers values
func NewPostV3ProjectidBadGateway() *PostV3ProjectidBadGateway {
	return &PostV3ProjectidBadGateway{}
}

/*PostV3ProjectidBadGateway handles this case with default header values.

Ethereum client error
*/
type PostV3ProjectidBadGateway struct {
}

func (o *PostV3ProjectidBadGateway) Error() string {
	return fmt.Sprintf("[POST /v3/{projectid}][%d] postV3ProjectidBadGateway ", 502)
}

func (o *PostV3ProjectidBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
