#!/bin/bash
#
# questions
# can we capture out of memory message?
# does relaunch work
#
# supervisor reference
# --watch comma separated list of files or folders, default '.'
# --extensions file extensions for folders, default: 'node|js'
# --exec the executable, default 'node'
# --no-restart-on error|exit, default all
# --help
# --quiet supress debug messages
# --?
echo "\n\n=== Tailing log at: $(date)"
tail -n0 log.txt &
supervisor --watch memfill.js,gomemfill.js gomemfill.js &>log.txt
