// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_cloud_logic : 'enable',
aws_cloud_logic_custom : '[{"id":"d8jlns5rpa","name":"ReactSample","description":"","endpoint":"https://d8jlns5rpa.execute-api.us-west-1.amazonaws.com/Development","region":"us-west-1","paths":["/items","/items/123"]}]',
aws_cognito_identity_pool_id : 'us-west-2:d0a64c3d-7b75-4cff-9cff-cf317e35e35a',
aws_cognito_region : 'us-west-2',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'awsreact-hosting-mobilehub-1151619533',
aws_content_delivery_bucket_region : 'us-west-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd3kiqoc45xkbr3.cloudfront.net',
aws_dynamodb : 'enable',
aws_dynamodb_all_tables_region : 'us-west-1',
aws_dynamodb_table_schemas : '[{"tableName":"awsreact-mobilehub-1151619533-bbq_orders","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-west-1","hashKey":"id"},{"tableName":"awsreact-mobilehub-1151619533-bbq_restaurants","attributes":[{"name":"id","type":"S"}],"indexes":[],"region":"us-west-1","hashKey":"id"},{"tableName":"awsreact-mobilehub-1151619533-bbq_menu_item","attributes":[{"name":"restaurant_id","type":"S"},{"name":"id","type":"S"}],"indexes":[],"region":"us-west-1","hashKey":"restaurant_id","rangeKey":"id"}]',
aws_mandatory_sign_in : 'enable',
aws_project_id : '92d26783-2afe-4e1b-903a-da8a1c7de27f',
aws_project_name : 'aws-react',
aws_project_region : 'us-west-1',
aws_resource_bucket_name : 'awsreact-deployments-mobilehub-1151619533',
aws_resource_name_prefix : 'awsreact-mobilehub-1151619533',
aws_sign_in_enabled : 'enable',
aws_user_pools : 'enable',
aws_user_pools_id : 'us-west-2_DJXWq0v19',
aws_user_pools_mfa_type : 'ON',
aws_user_pools_web_client_id : '7i9uhvf7mvb09ri3f54mom8fue',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});