#! /bin/bash
# basharithmetic
# bash integer algebra
# © 2013 Harald Rudell <harald.rudell@therudells.com> (http://haraldrudell.com) All rights reserved.

# http://www.gnu.org/software/bash/manual/bashref.html#Shell-Arithmetic

echo; echo; echo "=== $(basename $0) $(date --rfc-3339=s)"
LINENO= # make it work with sh
set -eu

A=$(date +%s%N)
echo "Shell arithmetic allows for integer evaluation"
echo "\$((...))"
XX=11
X=$((1+$XX))
#X++
echo "X:$X"
ELAPSED=$(($(date +%s%N) - A))
S=$((ELAPSED / 1000 % 1000000 + 1000000))
S="$((ELAPSED / 1000000000)).${S:1}"
echo "time: $S s"

echo "((...)) evaluates an arithmetic expression similar to [[..]]"

echo "Operators, precendence and associativity same as for C"

X=1
#X=X + 1
echo "X:$X"

echo; echo "conversion"
# 0
# 0x
# null unset = 0
# declare -i
# let
# [base#]n
# integer attribute
