// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MethodsResponse methods response
// swagger:model MethodsResponse
type MethodsResponse struct {

	// List of methods supported by the /v1/jsonrpc/{network}/{method} endpoint (GET)
	// Required: true
	Get []string `json:"get"`

	// List of methods supported by the /v1/jsonrpc/{network} endpoint (POST)
	// Required: true
	Post []string `json:"post"`
}

// Validate validates this methods response
func (m *MethodsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGet(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePost(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MethodsResponse) validateGet(formats strfmt.Registry) error {

	if err := validate.Required("get", "body", m.Get); err != nil {
		return err
	}

	return nil
}

func (m *MethodsResponse) validatePost(formats strfmt.Registry) error {

	if err := validate.Required("post", "body", m.Post); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MethodsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MethodsResponse) UnmarshalBinary(b []byte) error {
	var res MethodsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
