// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SymbolsResponse symbols response
// swagger:model SymbolsResponse
type SymbolsResponse struct {

	// List of supported symbols (currency pairs)
	Symbols []string `json:"symbols"`
}

// Validate validates this symbols response
func (m *SymbolsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SymbolsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SymbolsResponse) UnmarshalBinary(b []byte) error {
	var res SymbolsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
