// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TickerResponse ticker response
// swagger:model TickerResponse
type TickerResponse struct {

	// Ask at the exchange with the most volume
	Ask float64 `json:"ask,omitempty"`

	// Currency pair base
	Base string `json:"base,omitempty"`

	// Bid at the exchange with the most volume
	Bid float64 `json:"bid,omitempty"`

	// The exchange with the most volume
	Exchange string `json:"exchange,omitempty"`

	// Number of exchanges queried
	NumExchanges int64 `json:"num_exchanges,omitempty"`

	// Currency pair quote
	Quote string `json:"quote,omitempty"`

	// Unix timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// Total volume across all exchanges queried
	TotalVolume float64 `json:"total_volume,omitempty"`

	// Volume at the exchange with the most volume
	Volume float64 `json:"volume,omitempty"`
}

// Validate validates this ticker response
func (m *TickerResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TickerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TickerResponse) UnmarshalBinary(b []byte) error {
	var res TickerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
