const INDEX_INJECTION = 'index';
const UFE_ALL_PARTS = 'ufeAllParts';
const TPS_UFE_ALL_PARTS = 'TPSufeAllParts';
const RENDERTYPE = 'renderType=';

const EMPTY_TEMPLATE = 'Empty/Empty';

const DOCUMENT_TYPE = '<!DOCTYPE html>\n';

const TARGETER_QUERY_PARAMS = '__TARGETER_QUERY_PARAM__';

const ACTION_WATCHER_STATE_NAME = 'watcher';

const UFE_ENV_PRODUCTION = 'PROD';
const UFE_ENV_QA = 'QA';
const UFE_ENV_LOCAL = 'LOCAL';
const VALID_UFE_ENVS = [UFE_ENV_PRODUCTION, UFE_ENV_LOCAL, UFE_ENV_QA];

module.exports = {
    INDEX_INJECTION: INDEX_INJECTION,
    EMPTY_TEMPLATE: EMPTY_TEMPLATE,
    UFE_ALL_PARTS: UFE_ALL_PARTS,
    TPS_UFE_ALL_PARTS: TPS_UFE_ALL_PARTS,
    DOCUMENT_TYPE: DOCUMENT_TYPE,
    TARGETER_QUERY_PARAMS: TARGETER_QUERY_PARAMS,
    ACTION_WATCHER_STATE_NAME: ACTION_WATCHER_STATE_NAME,
    UFE_ENV_PRODUCTION: UFE_ENV_PRODUCTION,
    UFE_ENV_QA: UFE_ENV_QA,
    UFE_ENV_LOCAL: UFE_ENV_LOCAL,
    VALID_UFE_ENVS: VALID_UFE_ENVS,
    RENDERTYPE: RENDERTYPE
};



// WEBPACK FOOTER //
// ./public_ufe/js/utils/framework/Constants.js