Description: >
  Amazon CloudFormation template for EC2 instance

Parameters:

  AvailabilityZone:
    Type: String

  InstanceType:
    Type: String
    Default: t2.micro

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZone
      InstanceType:
        Ref: InstanceType
      #SecurityGroups:
      #- Ref: InstanceSecurityGroup
      #KeyName:
      #  Ref: KeyName
      ImageId: IMAGEID
