// jsdom1.js

// https://github.com/tmpvar/jsdom
var jsdom = require('jsdom')

/*
1. we want to use the full page-scripts and jquery while scraping a page

{ dom: 
   { level3: { core: [Object], xpath: undefined, events: {}, html: [Object] },
     ls: 
      { LSException: [Function: LSException],
        DOMImplementationLS: [Function: DOMImplementationLS],
        LSParser: [Function: LSParser],
        LSInput: [Function: LSInput],
        LSResourceResolver: [Function: LSResourceResolver],
        LSParserFilter: [Function: LSParserFilter],
        LSSerializer: [Function: LSSerializer],
        LSOutput: [Function: LSOutput],
        LSProgressEvent: [Function: LSProgressEvent],
        LSLoadEvent: [Function: LSLoadEvent],
        LSSerializerFilter: [Function: LSSerializerFilter] } },
  defaultLevel: 
   { languageProcessors: { javascript: [Function] },
     resourceLoader: 
      { load: [Function],
        enqueue: [Function],
        baseUrl: [Function],
        resolve: [Function],
        download: [Function],
        readFile: [Function] },
     HTMLCollection: [Function: HTMLCollection],
     HTMLOptionsCollection: [Function: HTMLCollection],
     HTMLDocument: [Function: HTMLDocument],
     HTMLElement: { [Function] _init: undefined },
     HTMLFormElement: { [Function] _init: undefined },
     HTMLLinkElement: { [Function] _init: [Function] },
     HTMLMetaElement: { [Function] _init: undefined },
     HTMLHtmlElement: { [Function] _init: undefined },
     HTMLHeadElement: { [Function] _init: undefined },
     HTMLTitleElement: { [Function] _init: undefined },
     HTMLIsIndexElement: { [Function] _init: undefined },
     HTMLStyleElement: { [Function] _init: [Function] },
     HTMLBodyElement: { [Function] _init: undefined },
     HTMLSelectElement: { [Function] _init: undefined },
     HTMLOptGroupElement: { [Function] _init: undefined },
     HTMLOptionElement: { [Function] _init: undefined },
     HTMLInputElement: { [Function] _init: undefined },
     HTMLTextAreaElement: { [Function] _init: undefined },
     HTMLButtonElement: { [Function] _init: undefined },
     HTMLLabelElement: { [Function] _init: undefined },
     HTMLFieldSetElement: { [Function] _init: undefined },
     HTMLLegendElement: { [Function] _init: undefined },
     HTMLUListElement: { [Function] _init: undefined },
     HTMLOListElement: { [Function] _init: undefined },
     HTMLDListElement: { [Function] _init: undefined },
     HTMLDirectoryElement: { [Function] _init: undefined },
     HTMLMenuElement: { [Function] _init: undefined },
     HTMLLIElement: { [Function] _init: undefined },
     HTMLDivElement: { [Function] _init: undefined },
     HTMLParagraphElement: { [Function] _init: undefined },
     HTMLHeadingElement: { [Function] _init: undefined },
     HTMLQuoteElement: { [Function] _init: undefined },
     HTMLPreElement: { [Function] _init: undefined },
     HTMLBRElement: { [Function] _init: undefined },
     HTMLBaseFontElement: { [Function] _init: undefined },
     HTMLFontElement: { [Function] _init: undefined },
     HTMLHRElement: { [Function] _init: undefined },
     HTMLModElement: { [Function] _init: undefined },
     HTMLAnchorElement: { [Function] _init: undefined },
     HTMLImageElement: { [Function] _init: undefined },
     HTMLObjectElement: { [Function] _init: undefined },
     HTMLParamElement: { [Function] _init: undefined },
     HTMLAppletElement: { [Function] _init: undefined },
     HTMLMapElement: { [Function] _init: undefined },
     HTMLAreaElement: { [Function] _init: undefined },
     HTMLScriptElement: { [Function] _init: [Function] },
     HTMLTableElement: { [Function] _init: undefined },
     HTMLTableCaptionElement: { [Function] _init: undefined },
     HTMLTableColElement: { [Function] _init: undefined },
     HTMLTableSectionElement: { [Function] _init: undefined },
     HTMLTableRowElement: { [Function] _init: undefined },
     HTMLTableCellElement: { [Function] _init: undefined },
     HTMLFrameSetElement: { [Function] _init: undefined },
     HTMLFrameElement: { [Function] _init: [Function] },
     HTMLIFrameElement: { [Function] _init: undefined } },
  browserAugmentation: [Function],
  windowAugmentation: [Function],
  availableDocumentFeatures: [Getter/Setter],
  defaultDocumentFeatures: [Getter/Setter],
  applyDocumentFeatures: [Getter/Setter],
  debugMode: false,
  createWindow: [Function],
  version: [Getter],
  level: [Function],
  jsdom: 
   { [Function]
     jQueryify: [Function],
     env: { [Function] processArguments: [Function] } },
  html: [Function],
  jQueryify: [Function],
  env: { [Function] processArguments: [Function] } }
*/

console.log(jsdom)