Description: >
  Amazon Cloud Creator Microservice template for CloudFront Stack
  To add a new function define the function role and the function itself following
  existing templates.

Parameters:

  LambdaVersion:
    Description: "Version md5 of the lambda function required to update existing stack"
    Type: String
    Default: "latest"

  S3BucketName:
    Description: "S3BucketName"
    Type: "String"

Resources:
  THELAMBDARole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "THELAMBDAPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: "*"

  THELAMBDA:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Sub THELAMBDA-${LambdaVersion}.zip
      Description: Lambda function that schedules updates
      Environment:
        Variables:
          NODE_ENV: production
      FunctionName: THELAMBDA
      Handler: "index.handler"
      MemorySize: 128
      Role: !GetAtt THELAMBDARole.Arn
      Runtime: "nodejs4.3"
      Timeout: 100