#!/bin/bash -eu
# scriptrun/webpack.config.js
# package.json babel nodecurrent
npm i --save-dev \
babel-cli \
babel-core \
babel-eslint \
babel-loader \
babel-plugin-transform-class-properties \
babel-plugin-transform-object-rest-spread \
babel-plugin-transform-runtime \
babel-preset-env \
babel-preset-node8 \
babel-runtime \
eslint \
eslint-config-fbjs \
eslint-loader \
eslint-plugin-babel \
eslint-plugin-flowtype \
eslint-plugin-jsx-a11y \
eslint-plugin-react \
eslint-plugin-relay \
react-dev-utils \
webpack
