#!/bin/bash -eu
# © 2017-present Harald Rudell <harald.rudell@gmail.com> (http://www.haraldrudell.com)
# All rights reserved.
doCmd () {
  echo "$*"
  "$@"
}

for P in package.json node_modules yarn.lock; do
  if [ -e "$P" ]; then
    doCmd rm -r "$P"
  fi
done
doCmd yarn init --yes
# doCmd yarn add es2049scripts --dev
doCmd yarn add ../../forks/ecmascript2049/packages/es2049scripts --dev
node -e "var pj = require('./package.json')
var s = Object(pj).scripts || (pj.scripts = {})
if (!s.start) s.start = 'es2049scripts -- node config'
require('fs').writeFileSync('package.json', JSON.stringify(pj, null, '  '))"
mkdir -p configes
cat <<EOF >configes/index.mjs
console.log('The next ReactJS version:')
f()
async function f () {
  for await (let v of [Promise.resolve(17)])
    console.log(v)
}
EOF
doCmd yarn start

